### PR TITLE
Using IdentityServer3 v2.0.1 instead of v2.0.1-build00181 to fix build

### PR DESCRIPTION
**Pull request by billpratt**
The logging sample currently using IdentityServer3 v2.0.1-build00181 and doesnt build if you dont have access to -build nuget packages

### CODE REVIEW

**Comment by brockallen** [comment]
All of our samples always point to the myget feeds. Are you saying you can't access them, or is the real problem that the version being referenced is no longer available on myget?

**Comment by billpratt** [comment]
I didnt realize that and assumed it was a mistake. I dont have the myget feed in my sources and the build was failing. I'll close this pull request.

**Comment by billpratt** [comment]
Is the myget feed documented somewhere?

**Comment by leastprivilege** [comment]
There should be a nuget.config in every sample - and VS should pick the myget feed up automatically.

**Comment by billpratt** [comment]
Found the issue. As @brockallen suggested 2.0.1-build00181
screenshot

**Comment by brockallen** [comment]
So yea, our myget feed deletes anything older than 5 or 10 versions. Version 195 is the last "pinned" version (that won't be deleted). We're happy for a PR for that update :)

**Comment by billpratt** [comment]
on it

**Comment by billpratt** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/pull/184

**Comment by brockallen** [comment]
merged, and thx

**Comment by billpratt** [comment]
np. If I get some time I'll update the others. Feel free to put something in and assign it to me

**Pull request closed without merging**
