### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by devlz303**
To prevent a possible problem when the message from the iframe is sent before the eventlistener is active, I propse to set the frame.src after setting the eventlistener

### CODE REVIEW

**Comment by devlz303** [comment]
I think I did something terribly wrong here. :-(

**Comment by leastprivilege** [comment]
:) no worries.

clone the repo
create a new branch
do just the one thing you want to fix on that branch
use that branch for the PR

**Comment by leastprivilege** [comment]
closing this one

**Comment by brockallen** [comment]
Let me guess -- github for windows?

**Comment by devlz303** [comment]
Yep. I've never worked with Github (we use SVN), so it's all new for me.
Maybe I have to follow a Github for Dummies course on Pluralsight. :)

**Comment by brockallen** [comment]
I wasn't making fun of you -- I was more making a comment about github for windows. We see these sort of accidental PRs all the time, so I think something about github for windows might be to blame (at least partially).

**Comment by devlz303** [comment]
I'm not offended by your comment. I am making fun of myself. ;)

**Comment by devlz303** [comment]
I am looking into this Git thing right now, but it is a bit confusing to me.
The steps I have take so far are:
- Clone the "dev" branch
- Created a new (local) branch from this "dev" branch
- Made a change in the local branch
- Commit the change in the local branch
- Uhhhm, what's next. Make a pull request?

But somehow I don't think this is the right way to do it. I can't create a remote branch because I don't have rights to do it. I will have to take a look at it this when I have more time for it.
I don't want to bother you with this, but can you just tell me if I'm on the right track?

**Comment by brockallen** [comment]
Look at SourceTree -- it's a nice UI that seems to make sense of git:
http://www.sourcetreeapp.com/

**Comment by devlz303** [comment]
Thanks, I will give it a go.

**Comment by leastprivilege** [comment]
* Clone the "dev" branch
* Created a new (local) branch from this "dev" branch
* Made a change in the local branch
* Commit the change in the local branch
* Push the branch to your repo on github
* Make a pull request on github

**Comment by devlz303** [comment]
I realy feel like a fool, but I am stuck at "Push the branch to your repo on github".
Do you mean my own repository or a branch on the IdentityServer repository? A branch on the IdentityServer repository is not working (I don't have rights) and to my own, well.. I just can't figure out how this can be done.

**Comment by leastprivilege** [comment]
https://guides.github.com/activities/contributing-to-open-source/

**Comment by devlz303** [comment]
Thank you for the link. I think this is the information I need.

**Comment by devlz303** [comment]
Thanks for helping me out with this Brock & Dominick. I think I have successfuly made my first pull request. :)

**Pull request closed without merging**
