### PR TITLE
Pull request for issue #111 and #112

### PR DESCRIPTION
**Pull request by devlz303**

### CODE REVIEW

**Comment by devlz303** [comment]
This pull request is related to issue #112

**Comment by devlz303** [comment]
I've already signed the cla for the Thinktecture.IdentityServer once (because there isn't a cla for the Samples repository). Do I have to sign the agreement for each pull request?

**Comment by brockallen** [comment]
No -- you should only have to sign it for the project (so IdentityServer3 in this case).

**Comment by devlz303** [comment]
No, I have only one account (as far as I know :)), and I have signed the agreement already for my previous pull request.

**Comment by devlz303** [comment]
I'm closing this pull request because the fix for issue#112 isn't working because in IE9 hash fragment is when redirecting to the callback page is removed. So for IE9 the implicit flow still isn't going to work.

**Comment by devlz303** [comment]
Update: After all the fix IS working. However, after retrieving the tokens I needed to make a calls to Web API's using the access token. For this I implemented the xdomain javascript library which interfered with the oidc.js code. After removing the xdomain library I could sign in again. I will take a look if I can make it work even whith the xdomain library in place.

**Comment by brockallen** [comment]
So I'm a bit behind on this issue -- what's the status and are you asking us to do anything?

**Comment by dannycallaghan** [comment]
Are there any updates on this? We're having the same issue, and would love to see a fix in place.

**Comment by devlz303** [comment]
Well, we are using a modified version of the oidc.js. I have modified the getJSON function inside the DefaultHttpRequest function. Below you will find my version of the getJSON function.

Now, with this change in place you should be able to sign in with IE9. However, if your web api's are on a different domain you can't use the XDomainRequest object because you can't set additional headers with it (so you can't add access tokens to the header).
To make this work our callback page redirects to the "main" application, where we have configured the xdomain library (https://github.com/jpillora/xdomain). See below for an example.

For us this "solution" is working fine and we are able to use the application in IE9.

Worth mentioning: this library has been moved to https://github.com/IdentityModel/oidc-client and here https://github.com/IdentityModel/oidc-token-manager so if you still have problems you should post your issues there.

```javascript
this.getJSON = function (url, config) {
            return _promiseFactory.create(function (resolve, reject) {

                try {

                    var xr = null;

                    if (url.indexOf(window.location.protocol + '//' + window.location.host + "/") == -1 && (typeof XDomainRequest != "undefined")) {
                        log("cross-domain request using IE8/9");
                        xr = new XDomainRequest();
                        xr.open("GET", url);
                    }
                    else {
                        xr = new XMLHttpRequest();
                        xr.open("GET", url);

                        try {
                            xr.responseType = "json";
                        }
                        catch (e) {
                            log("Setting json responseType not supported for " + navigator.userAgent);
                        }

                        if (config) {
                            if (config.headers) {
                                setHeaders(xr, config.headers);
                            }
                        }
                    }

                    xr.onload = function () {
                        try {
                            var response = null;
                            if (xr.status === 200) {
                                response = xr.response;
                            }
                            else if (typeof xr.status == "undefined" && typeof xr.responseText != "undefined") {
                                response = xr.responseText;
                            }
                            else {
                                reject(Error(xr.statusText + "(" + xr.status + ")"));
                            }

                            if (typeof response === "string") {
                                response = JSON.parse(response);
                            }
                            resolve(response);
                        }
                        catch (err) {
                            reject(err);
                        }
                    };

                    xr.onerror = function () {
                        reject(Error("Network error"));
                    };

                    xr.send();
                }
                catch (err) {
                    return reject(err);
                }
            });
        };
```

**Comment by dannycallaghan** [comment]
Thank you, that's a great start for us, we'll give it a go.

**Comment by dannycallaghan** [comment]
Thanks @devlz303, I've managed to get IE9 working, using your rewritten getJSON function.

Just a FYI for anyone else who might be using this, I found that IE9 was failing to make one of the calls, and not showing any errors. Banged my head against the wall for some time, then managed to find this:

http://stackoverflow.com/questions/8058446/ie-xdomainrequest-not-always-work

It turns out that - in IE9 - unless you specify all possible events for the XDomainRequest call, it can silently fail. Editing the above getJSON, I added the following:

```javascript

xr.onprogress = function () {}

xr.ontimeout = function () {}

```

And IE9 started making the call successfully. Crazy.

**Comment by devlz303** [comment]
Hi Danny,
Good to hear you've got it working now. I have not ran into the issue of the failing calls myself.
Thanks for the update!

**Pull request closed without merging**
