### PR TITLE
adds powershell script for installing certificates

### PR DESCRIPTION
**Pull request by patrickhuber**
Adds a powershell script for installing the certificates instead of using mmc. I found this to be much easier to use than clicking around to get setup.

### CODE REVIEW

**Comment by leastprivilege** [comment]
hi, 

thanks - but why do you need to install those certs?

**Comment by brockallen** [comment]
@patrickhuber any update?

**Comment by patrickhuber** [comment]
For testing on a dev workstation and consuming tokens. The readme.md in the
same folder states all the reasons you would want to install the certs, the
script just makes getting running easier.

**Comment by brockallen** [comment]
Ok. @leastprivilege thoughts?

Also, @patrickhuber you've still not signed the CLA.

**Comment by patrickhuber** [comment]
I signed it under prhuber@gmail.com, it said it emailed Dominick. Not sure
how to link it to my github account, so if you have any pointers, I'd
appreciate it.

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
