### PR TITLE
Move the frame.src =url call to the end of the method to make sure the f...

### PR DESCRIPTION
**Pull request by devlz303**
...rame.src is set after adding the eventlistener. This is done to prevent message from the frame being posted before the listener is active.

This change is a fix for issue #101.

### CODE REVIEW

**Comment by brockallen** [comment]
CLA signed?

**Comment by leastprivilege** [comment]
We don't have one for the samples. Should we?

**Comment by devlz303** [comment]
I've signed a CLA, but it's for the IdentityServer project.

**Comment by leastprivilege** [comment]
That's fine thanks!

**Comment by brockallen** [comment]
thanks!

**Pull request merged**
